In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# 선택지 dictionary화 하기
food_choice = {
    '제육볶음': ['한식', '일상', '돼지고기'],
    '닭도리탕': ['한식', '술안주', '닭고기'],
    '된장찌개': ['한식', '원팬스피디', '콩견과류'],
    '비빔밥': ['한식', '다이어트', '채소'],
    '치킨커리': ['기타', '일상', '닭고기'],
    '쌀국수': ['기타', '일상', '면'],
    '마라탕': ['기타', '술안주', '채소'],
    '토마토파스타': ['양식', '원팬스피디', '면류'],
    '스테이크': ['양식', '일상', '소고기'],
    '초밥': ['일식', '일상', '해물'],
}
# 음식 카테고리들
kind = ['한식', '양식', '일식','기타s']
ingred = ['소고기', '돼지고기', '닭고기', '육류', '채소', '생선', '해물', '쌀', '밀가루', '면', '콩견과류', '달걀유제품', '가공식품류', '기타']
situation = ['모임용', '원팬스피디', '술안주', '일상', '다이어트', '디저트']

In [12]:
df = pd.read_csv('./data./cate_clean.csv')
# df[['종류별 카테고리','상황별 카테고리','재료별 카테고리']]

# df['종류별 카테고리'] +  ' ' + df['상황별 카테고리'] + ' ' + df['재료별 카테고리']

In [13]:
# df['cate'] = df['종류별 카테고리'] +  ' ' + df['상황별 카테고리'] + ' ' + df['재료별 카테고리']
data = df['cate'].tolist()

In [14]:
data

['한식 일상 생선',
 '한식 일상 콩견과류',
 '한식 술안주 채소',
 '한식 일상 돼지고기',
 '한식 모임용 소고기',
 '한식 일상 돼지고기',
 '한식 일상 면류',
 '한식 일상 소고기',
 '한식 원팬스피디 닭고기',
 '한식 술안주 밀가루',
 '한식 일상 달걀유제품',
 '한식 일상 면류',
 '한식 일상 가공식품류',
 '한식 원팬스피디 쌀류',
 '한식 일상 채소',
 '한식 다이어트 채소',
 '한식 일상 면류',
 '한식 원팬스피디 채소',
 '한식 술안주 콩견과류',
 '한식 일상 해물',
 '한식 원팬스피디 면류',
 '한식 일상 돼지고기',
 '한식 술안주 밀가루',
 '한식 술안주 채소',
 '한식 다이어트 채소',
 '한식 다이어트 채소',
 '한식 다이어트 채소',
 '한식 일상 소고기',
 '한식 일상 면류',
 '한식 술안주 소고기',
 '한식 술안주 돼지고기',
 '한식 일상 밀가루',
 '한식 다이어트 돼지고기',
 '한식 일상 콩견과류',
 '한식 일상 쌀류',
 '한식 일상 밀가루',
 '한식 원팬스피디 채소',
 '한식 원팬스피디 쌀류',
 '한식 일상 달걀유제품',
 '한식 일상 면류',
 '한식 일상 해물',
 '한식 다이어트 해물',
 '한식 일상 채소',
 '한식 일상 쌀류',
 '한식 일상 면류',
 '한식 원팬스피디 가공식품류',
 '한식 일상 해물',
 '한식 술안주 쌀류',
 '한식 다이어트 채소',
 '한식 일상 해물',
 '기타식 모임용 해물',
 '기타식 디저트 밀가루',
 '기타식 원팬스피디 채소',
 '기타식 술안주 돼지고기',
 '기타식 술안주 가공식품류',
 '기타식 술안주 해물',
 '기타식 술안주 닭고기',
 '기타식 일상 닭고기',
 '기타식 일상 달걀유제품',
 '기타식 일상 달걀유제품',
 '기타식 일상 닭고기',
 '기타식 일상 해물',
 '기타식 원팬스피디 콩견과류',
 '기타식 일상 면류',
 '기타식 일상 해물',
 '기타식 일상 돼지고기',
 '기타식 일상 면류',


In [9]:
tfidf = TfidfVectorizer()
all_item_tfidf_vector = tfidf.fit_transform(data).toarray()

In [7]:
all_item_tfidf_vector.shape

(200, 23)

In [15]:
cnt_vect = CountVectorizer()
cnt_vectors = cnt_vect.fit_transform(data).toarray()
cnt_vectors

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
base_data = cnt_vectors * 23 / np.exp(tfidf.idf_)
base_data

array([[0.        , 0.        , 0.        , ..., 0.        , 2.14687853,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.33676526, 2.14687853,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 2.14687853,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [7]:
sample = {
    '제육볶음': ['한식', '일상', '돼지고기'],
    '된장찌개': ['한식', '원팬스피디', '콩견과류'],
    '토마토파스타': ['양식', '원팬스피디', '면류'],
}


sample_data = sum(sample.values(), [])
sample_data

['한식', '일상', '돼지고기', '한식', '원팬스피디', '콩견과류', '양식', '원팬스피디', '면류']

In [16]:
selected_category_vector = np.zeros(cnt_vectors.shape[1])
selected_category_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [17]:
for term in sample_data:
    idx = cnt_vect.vocabulary_[term]
    selected_category_vector[idx] = (23 / np.exp(tfidf.idf_))[idx]
selected_category_vector

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.84191315, 0.        , 0.96820012, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       2.14687853, 1.59963498, 3.78860917, 0.        , 0.        ,
       0.33676526, 2.14687853, 0.        ])

In [18]:
cnt_vect.vocabulary_[term]

8

In [19]:
sims = cosine_similarity(cnt_vectors, selected_category_vector.reshape(1, -1))
sims

array([[0.64888826],
       [0.68570462],
       [0.23470426],
       [0.74092915],
       [0.23470426],
       [0.74092915],
       [0.75473528],
       [0.64888826],
       [0.40958195],
       [0.23470426],
       [0.64888826],
       [0.75473528],
       [0.64888826],
       [0.40958195],
       [0.64888826],
       [0.23470426],
       [0.75473528],
       [0.40958195],
       [0.27152062],
       [0.64888826],
       [0.51542897],
       [0.74092915],
       [0.23470426],
       [0.23470426],
       [0.23470426],
       [0.23470426],
       [0.23470426],
       [0.64888826],
       [0.75473528],
       [0.23470426],
       [0.32674515],
       [0.64888826],
       [0.32674515],
       [0.68570462],
       [0.64888826],
       [0.64888826],
       [0.40958195],
       [0.40958195],
       [0.64888826],
       [0.75473528],
       [0.64888826],
       [0.23470426],
       [0.64888826],
       [0.64888826],
       [0.75473528],
       [0.40958195],
       [0.64888826],
       [0.234

In [21]:
menu_list = np.array(cnt_vect.vocabulary_.keys())
# recommend_index = np.delete(sims.flatten(), [0, 6, 9]).argsort()
recommended_index = sims.flatten().argsort()[::-1]
recommended_index

array([ 28,  16,  11,   6,  44,  39,   5,   3,  21, 150,   1,  33, 161,
       163, 157, 164,  14, 155, 153,  19,  34,  27,  31,  35,  38,  40,
        42,  43,  46,  49,  12,   0, 194,   7, 190, 191, 172,  10, 177,
       192, 180, 195, 193,  66,  67,  82, 140,  80,  87,  63,  20, 176,
       175, 174, 173, 171, 170,  73, 131,  65, 138, 110,  83, 127,  57,
        58,  89, 120, 113, 111, 102, 108, 105, 124,  70, 126,  76,  72,
        90,  91,  60,  93,  94, 149, 146,  77,  61,  79, 139,  59, 103,
        81,  96, 130,  97,  64, 169,  45,  13,  37,  36, 185, 179, 151,
        17, 158,   8,  32,  30, 181, 160,  71, 141,  18,  74, 100,  41,
         9,  29,  26,   2,  25,  24,  23,  22,  47,  48,  15,   4, 199,
       167, 198, 165, 159, 166, 156, 154, 168, 178, 152, 182, 184, 183,
       186, 187, 188, 189, 196, 197, 162,  62, 116, 128, 123, 136, 119,
       147, 117, 101, 109, 104, 135,  52,  86, 134,  53,  92,  84, 133,
       112, 145,  69, 148, 143, 144, 125, 142, 137,  75,  78,  8

In [22]:
df.iloc[recommended_index].head(10)

cate
28     한식 일상 면류
16     한식 일상 면류
11     한식 일상 면류
6      한식 일상 면류
44     한식 일상 면류
39     한식 일상 면류
5    한식 일상 돼지고기
3    한식 일상 돼지고기
21   한식 일상 돼지고기
150  양식 일상 돼지고기